version: '3'
services:
  node:
    image: node:latest
    working_dir: /var/www/html
    container_name: node
    volumes:
      - ./code/node_modules:/var/www/html/node_modules
      - ./code/package.json:/var/www/html/package.json

  composer:
    image: composer:1.9.0
    working_dir: /var/www/html
    container_name: composer
    depends_on:
      - "webserver"
    volumes:
      - ./code/vendor:/var/www/html/vendor
      - ./code/composer.json:/var/www/html/composer.json

  #Apache Service
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:8080"
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_LYNX: "cat"
    volumes:
      - ./code:/var/www/html
      - ./services/httpd/conf.d/sites-enabled/server.conf:/etc/apache2/ports.conf
      - ./services/cron.d/laravel-scheduler:/var/www/laravel-scheduler
      - ./services/cron.d/crontab:/etc/crontab
      - ./services/cron.d/log:/var/log/cron
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: pwd4s20r
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./services/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local